lint:
  stage: build
  script:
  - pip install yapf
  - yapf --recursive .
  only:
  - pushes


unittest:
 stage: test
 dependencies: 
 - lint
 script:
 - pip install -r requirements.txt
 - pytest project/
 only:
 - pushes